// FEditar aqui se mostraran los datos anteriores para su posterior edicion, estos datos seran recogidos
// de la bd por el PreparedStatement y podran ser modificados por los campos de texto.

package Calificaciones01;

import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;

public class FEditar extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement PStatement = null;
    public String id = null;
    public FEditar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBlancoFondo = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lbPlan = new javax.swing.JLabel();
        lbMateria = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbEquipo = new javax.swing.JLabel();
        lbSecuencia = new javax.swing.JLabel();
        lbPromedio = new javax.swing.JLabel();
        lbSexo = new javax.swing.JLabel();
        lbD3 = new javax.swing.JLabel();
        lbD2 = new javax.swing.JLabel();
        lbD1 = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        tfNumeroLista = new javax.swing.JTextField();
        lbNumeroLista = new javax.swing.JLabel();
        IconoUsuario = new javax.swing.JLabel();
        PanelGuinda = new javax.swing.JPanel();
        tfSexo = new javax.swing.JTextField();
        tfCarrera = new javax.swing.JTextField();
        tfMateria = new javax.swing.JTextField();
        tfPlan = new javax.swing.JTextField();
        tfD1 = new javax.swing.JTextField();
        tfD2 = new javax.swing.JTextField();
        tfD3 = new javax.swing.JTextField();
        tfPromedio = new javax.swing.JTextField();
        tfSecuencia = new javax.swing.JTextField();
        tfEquipo = new javax.swing.JTextField();
        lbTituloEditar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumnos");
        setBounds(new java.awt.Rectangle(0, 0, 900, 500));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelBlancoFondo.setBackground(new java.awt.Color(255, 255, 255));

        btnAtras.setBackground(new java.awt.Color(153, 0, 255));
        btnAtras.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/source_icons_arrow-left.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(204, 204, 0));
        btnActualizar.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/source_icons_refresh-double.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lbPlan.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbPlan.setForeground(new java.awt.Color(0, 0, 0));
        lbPlan.setText("Plan:");

        lbMateria.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbMateria.setForeground(new java.awt.Color(0, 0, 0));
        lbMateria.setText("Materia:");

        lbCarrera.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbCarrera.setForeground(new java.awt.Color(0, 0, 0));
        lbCarrera.setText("Carrera:");

        lbEquipo.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbEquipo.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo.setText("Equipo:");

        lbSecuencia.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbSecuencia.setForeground(new java.awt.Color(0, 0, 0));
        lbSecuencia.setText("Secuencia:");

        lbPromedio.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbPromedio.setForeground(new java.awt.Color(0, 0, 0));
        lbPromedio.setText("Promedio:");

        lbSexo.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(0, 0, 0));
        lbSexo.setText("Sexo:");

        lbD3.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbD3.setForeground(new java.awt.Color(0, 0, 0));
        lbD3.setText("D3:");

        lbD2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbD2.setForeground(new java.awt.Color(0, 0, 0));
        lbD2.setText("D2:");

        lbD1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbD1.setForeground(new java.awt.Color(0, 0, 0));
        lbD1.setText("D1:");

        lbApellido.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbApellido.setForeground(new java.awt.Color(0, 0, 0));
        lbApellido.setText("Primer Apellido:");

        lbNombre.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("Nombre:");

        lbNumeroLista.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbNumeroLista.setForeground(new java.awt.Color(0, 0, 0));
        lbNumeroLista.setText("Numero de Lista:");

        IconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/profile-user.png"))); // NOI18N

        PanelGuinda.setBackground(new java.awt.Color(108, 19, 43));

        javax.swing.GroupLayout PanelGuindaLayout = new javax.swing.GroupLayout(PanelGuinda);
        PanelGuinda.setLayout(PanelGuindaLayout);
        PanelGuindaLayout.setHorizontalGroup(
            PanelGuindaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelGuindaLayout.setVerticalGroup(
            PanelGuindaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lbTituloEditar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lbTituloEditar.setForeground(new java.awt.Color(0, 0, 0));
        lbTituloEditar.setText("Editar");

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/source_icons_undo.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBlancoFondoLayout = new javax.swing.GroupLayout(PanelBlancoFondo);
        PanelBlancoFondo.setLayout(PanelBlancoFondoLayout);
        PanelBlancoFondoLayout.setHorizontalGroup(
            PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumeroLista)
                    .addComponent(lbNombre)
                    .addComponent(lbApellido)
                    .addComponent(lbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMateria)
                    .addComponent(lbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addComponent(tfMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre)
                            .addComponent(tfNumeroLista)
                            .addComponent(tfApellido)
                            .addComponent(tfSexo)
                            .addComponent(tfCarrera)
                            .addComponent(tfPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(tfSecuencia)
                                    .addComponent(tfPromedio))
                                .addGap(123, 123, 123)
                                .addComponent(lbTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbD1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbD2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbD3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfD1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(tfD2)
                                    .addComponent(tfD3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IconoUsuario)))
                        .addGap(59, 59, 59))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBlancoFondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(226, 226, 226))
            .addComponent(PanelGuinda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBlancoFondoLayout.setVerticalGroup(
            PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBlancoFondoLayout.createSequentialGroup()
                .addComponent(PanelGuinda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumeroLista)
                            .addComponent(tfNumeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbD1)
                            .addComponent(tfD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombre)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbD2)
                            .addComponent(tfD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbApellido)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbD3)
                            .addComponent(tfD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSexo)
                            .addComponent(tfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPromedio)
                            .addComponent(tfPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCarrera)
                            .addComponent(tfCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSecuencia)
                            .addComponent(tfSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMateria)
                            .addComponent(lbEquipo)
                            .addComponent(tfEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPlan)
                            .addComponent(tfPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAtras)
                                .addComponent(btnActualizar)))
                        .addGap(15, 15, 15))
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addComponent(IconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTituloEditar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlancoFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlancoFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = DBConexion.DBConexión();
        
        // Se utiliza la condicion if para definir el la fila seleccionada 
        
        String sql = "SELECT * FROM alumnos WHERE NumeroLista = "+id+"";
        try {
           PStatement = conn.prepareStatement(sql);
           rs = PStatement.executeQuery();
           if(rs.next()){
               // Imprime los datos de la bd en los campos de texto correspondientes
               tfNumeroLista.setText(rs.getString("NumeroLista"));
               tfNombre.setText(rs.getString("Nombre"));
               tfApellido.setText(rs.getString("ApellidoPaterno"));
               tfSexo.setText(rs.getString("Sexo"));
               tfCarrera.setText(rs.getString("Carrera"));
               tfMateria.setText(rs.getString("Materia"));
               tfPlan.setText(rs.getString("PlanEstudios"));
               tfD1.setText(rs.getString("D1"));
               tfD2.setText(rs.getString("D2"));
               tfD3.setText(rs.getString("D3"));
               tfPromedio.setText(rs.getString("PromedioR"));
               tfSecuencia.setText(rs.getString("Secuencia"));
               tfEquipo.setText(rs.getString("NoEquipo"));
           }
           
       } catch(Exception ex) {
           System.out.println("Error: "+ex);
       }
    }//GEN-LAST:event_formWindowOpened

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Trae el texto como un añadir pero esta vez se usara UPDATE de sql
        String lNumeroLista = tfNumeroLista.getText();
        String lNombre = tfNombre.getText();
        String lApellido = tfApellido.getText(); //Aqui
        String lSexo = tfSexo.getText();
        String lCarrera = tfCarrera.getText();
        String lMateria = tfMateria.getText();
        String lPlan = tfPlan.getText();
        String lD1 = tfD1.getText();
        String lD2 = tfD2.getText();
        String lD3 = tfD3.getText();
        String lPromedio = tfPromedio.getText();
        String lSecuencia = tfSecuencia.getText();
        String lEquipo = tfEquipo.getText();
        
        String sql = "UPDATE alumnos SET NumeroLista='"+lNumeroLista+"', Nombre='"+lNombre+"', ApellidoPaterno='"+lApellido+"', Sexo='"+lSexo+"', Carrera='"+lCarrera+"', Materia='"+lMateria+"', PlanEstudios='"+lPlan+"', D1='"+lD1+"', D2='"+lD2+"', D3='"+lD3+"', PromedioR='"+lPromedio+"', Secuencia='"+lSecuencia+"', NoEquipo='"+lEquipo+"' WHERE NumeroLista = "+id+"";
        try {
            stmt = conn.createStatement();
            if(stmt.executeUpdate(sql) == 1){
                JOptionPane.showMessageDialog(null,"Se actualizo con exito","ALERTA",JOptionPane.INFORMATION_MESSAGE);
                // Automaticamente regresara a FRegistro una vez actualizado el dato.
                new FRegistro().setVisible(true);
                this.setVisible(false);
                this.dispose();
            } else {
              JOptionPane.showMessageDialog(null,"Error al editar","ALERTA",JOptionPane.WARNING_MESSAGE);
            }
           
       } catch(Exception ex) {
           System.out.println("Error: "+ex);
       }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // Boton Atras regresa al formulario anterior FRegistro
        new FRegistro().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Boton Limpiar limpia todos los campos y ya...
        tfNumeroLista.setText(null);
        tfNombre.setText(null);
        tfApellido.setText(null);
        tfSexo.setText(null);
        tfCarrera.setText(null);
        tfMateria.setText(null);
        tfPlan.setText(null);
        tfD1.setText(null);
        tfD2.setText(null);
        tfD3.setText(null);
        tfPromedio.setText(null);
        tfSecuencia.setText(null);
        tfEquipo.setText(null);

        tfNumeroLista.requestFocus();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEditar().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoUsuario;
    private javax.swing.JPanel PanelBlancoFondo;
    private javax.swing.JPanel PanelGuinda;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbD1;
    private javax.swing.JLabel lbD2;
    private javax.swing.JLabel lbD3;
    private javax.swing.JLabel lbEquipo;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumeroLista;
    private javax.swing.JLabel lbPlan;
    private javax.swing.JLabel lbPromedio;
    private javax.swing.JLabel lbSecuencia;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTituloEditar;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCarrera;
    private javax.swing.JTextField tfD1;
    private javax.swing.JTextField tfD2;
    private javax.swing.JTextField tfD3;
    private javax.swing.JTextField tfEquipo;
    private javax.swing.JTextField tfMateria;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNumeroLista;
    private javax.swing.JTextField tfPlan;
    private javax.swing.JTextField tfPromedio;
    private javax.swing.JTextField tfSecuencia;
    private javax.swing.JTextField tfSexo;
    // End of variables declaration//GEN-END:variables
}
