// Aqui solo se muestran los datos de la persona seleccionada, no se puede editar desde aqui
package Calificaciones01;

import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;

public class FVisualizar extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement PStatement = null;
    ResultSet rs = null;
    public String id = null;
    
    public FVisualizar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBlancoFondo = new javax.swing.JPanel();
        lbNL = new javax.swing.JLabel();
        lbNmbre = new javax.swing.JLabel();
        lbPA = new javax.swing.JLabel();
        lbSx = new javax.swing.JLabel();
        lbCrra = new javax.swing.JLabel();
        lbMtria = new javax.swing.JLabel();
        lbPln = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbNumeroLista = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lbEqpo = new javax.swing.JLabel();
        lbSecia = new javax.swing.JLabel();
        lbPrmedio = new javax.swing.JLabel();
        lbDep3 = new javax.swing.JLabel();
        lbDep2 = new javax.swing.JLabel();
        lbDep1 = new javax.swing.JLabel();
        PanelGuindaFondo = new javax.swing.JPanel();
        lbSexo = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbMateria = new javax.swing.JLabel();
        lbPlan = new javax.swing.JLabel();
        lbD1 = new javax.swing.JLabel();
        lbD2 = new javax.swing.JLabel();
        lbD3 = new javax.swing.JLabel();
        lbPromedio = new javax.swing.JLabel();
        lbSecuencia = new javax.swing.JLabel();
        lbEquipo = new javax.swing.JLabel();
        lbImagenUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alummos");
        setBounds(new java.awt.Rectangle(0, 0, 900, 500));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelBlancoFondo.setBackground(new java.awt.Color(255, 255, 255));

        lbNL.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbNL.setForeground(new java.awt.Color(0, 0, 0));
        lbNL.setText("Numero de Lista:");

        lbNmbre.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbNmbre.setForeground(new java.awt.Color(0, 0, 0));
        lbNmbre.setText("Nombre:");

        lbPA.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbPA.setForeground(new java.awt.Color(0, 0, 0));
        lbPA.setText("Primer Apellido:");

        lbSx.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbSx.setForeground(new java.awt.Color(0, 0, 0));
        lbSx.setText("Sexo:");

        lbCrra.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbCrra.setForeground(new java.awt.Color(0, 0, 0));
        lbCrra.setText("Carrera:");

        lbMtria.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbMtria.setForeground(new java.awt.Color(0, 0, 0));
        lbMtria.setText("Materia:");

        lbPln.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbPln.setForeground(new java.awt.Color(0, 0, 0));
        lbPln.setText("Plan:");

        lbApellido.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbApellido.setForeground(new java.awt.Color(0, 0, 0));
        lbApellido.setText("Ejemplo");

        lbNombre.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("Ejemplo");

        lbNumeroLista.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbNumeroLista.setForeground(new java.awt.Color(0, 0, 0));
        lbNumeroLista.setText("Ejemplo");

        btnAtras.setBackground(new java.awt.Color(153, 0, 255));
        btnAtras.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/source_icons_arrow-left.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lbEqpo.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbEqpo.setForeground(new java.awt.Color(0, 0, 0));
        lbEqpo.setText("Equipo:");

        lbSecia.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbSecia.setForeground(new java.awt.Color(0, 0, 0));
        lbSecia.setText("Secuencia:");

        lbPrmedio.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbPrmedio.setForeground(new java.awt.Color(0, 0, 0));
        lbPrmedio.setText("Promedio:");

        lbDep3.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbDep3.setForeground(new java.awt.Color(0, 0, 0));
        lbDep3.setText("D3:");

        lbDep2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbDep2.setForeground(new java.awt.Color(0, 0, 0));
        lbDep2.setText("D2:");

        lbDep1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lbDep1.setForeground(new java.awt.Color(0, 0, 0));
        lbDep1.setText("D1:");

        PanelGuindaFondo.setBackground(new java.awt.Color(108, 19, 43));

        javax.swing.GroupLayout PanelGuindaFondoLayout = new javax.swing.GroupLayout(PanelGuindaFondo);
        PanelGuindaFondo.setLayout(PanelGuindaFondoLayout);
        PanelGuindaFondoLayout.setHorizontalGroup(
            PanelGuindaFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelGuindaFondoLayout.setVerticalGroup(
            PanelGuindaFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lbSexo.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(0, 0, 0));
        lbSexo.setText("Ejemplo");

        lbCarrera.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        lbCarrera.setForeground(new java.awt.Color(0, 0, 0));
        lbCarrera.setText("Ejemplo");

        lbMateria.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbMateria.setForeground(new java.awt.Color(0, 0, 0));
        lbMateria.setText("Ejemplo");

        lbPlan.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbPlan.setForeground(new java.awt.Color(0, 0, 0));
        lbPlan.setText("Ejemplo");

        lbD1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbD1.setForeground(new java.awt.Color(0, 0, 0));
        lbD1.setText("Ejemplo");

        lbD2.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbD2.setForeground(new java.awt.Color(0, 0, 0));
        lbD2.setText("Ejemplo");

        lbD3.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbD3.setForeground(new java.awt.Color(0, 0, 0));
        lbD3.setText("Ejemplo");

        lbPromedio.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbPromedio.setForeground(new java.awt.Color(0, 0, 0));
        lbPromedio.setText("Ejemplo");

        lbSecuencia.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbSecuencia.setForeground(new java.awt.Color(0, 0, 0));
        lbSecuencia.setText("Ejemplo");

        lbEquipo.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbEquipo.setForeground(new java.awt.Color(0, 0, 0));
        lbEquipo.setText("Ejemplo");

        lbImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/profile-user.png"))); // NOI18N

        javax.swing.GroupLayout PanelBlancoFondoLayout = new javax.swing.GroupLayout(PanelBlancoFondo);
        PanelBlancoFondo.setLayout(PanelBlancoFondoLayout);
        PanelBlancoFondoLayout.setHorizontalGroup(
            PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGuindaFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBlancoFondoLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addComponent(lbNL)
                        .addGap(52, 52, 52)
                        .addComponent(lbNumeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                            .addComponent(lbPln, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                            .addComponent(lbMtria)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBlancoFondoLayout.createSequentialGroup()
                            .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbNmbre)
                                .addComponent(lbPA)
                                .addComponent(lbSx, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCrra, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(127, 127, 127)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDep1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDep2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDep3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSecia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEqpo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbD1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(lbD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbD3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(lbImagenUser))
                    .addComponent(lbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        PanelBlancoFondoLayout.setVerticalGroup(
            PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                .addComponent(PanelGuindaFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDep1)
                    .addComponent(lbNL)
                    .addComponent(lbNumeroLista)
                    .addComponent(lbD1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDep2)
                    .addComponent(lbNombre)
                    .addComponent(lbNmbre)
                    .addComponent(lbD2))
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDep3)
                            .addComponent(lbPA)
                            .addComponent(lbApellido)
                            .addComponent(lbD3))
                        .addGap(30, 30, 30)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSx)
                            .addComponent(lbPrmedio)
                            .addComponent(lbSexo)
                            .addComponent(lbPromedio))
                        .addGap(30, 30, 30)
                        .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCrra)
                            .addComponent(lbSecia)
                            .addComponent(lbCarrera)
                            .addComponent(lbSecuencia)))
                    .addGroup(PanelBlancoFondoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbImagenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMtria)
                    .addComponent(lbMateria)
                    .addComponent(lbEquipo)
                    .addComponent(lbEqpo))
                .addGap(39, 39, 39)
                .addGroup(PanelBlancoFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPln)
                    .addComponent(lbPlan))
                .addGap(18, 18, 18)
                .addComponent(btnAtras)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlancoFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlancoFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               conn = DBConexion.DBConexión();
          String sql = "SELECT * FROM alumnos WHERE NumeroLista = "+id+"";
       try {
           
           PStatement = conn.prepareStatement(sql);
           rs = PStatement.executeQuery();
            
           //Aqui se muestran los datos del alumno seleccionado consultandolo en la bd.
           
           if(rs.next()){
               lbNumeroLista.setText(rs.getString("NumeroLista"));
               lbNombre.setText(rs.getString("Nombre"));
               lbApellido.setText(rs.getString("ApellidoPaterno"));
               lbSexo.setText(rs.getString("Sexo"));
               lbCarrera.setText(rs.getString("Carrera"));
               lbMateria.setText(rs.getString("Materia"));
               lbPlan.setText(rs.getString("PlanEstudios"));
               lbD1.setText(rs.getString("D1"));
               lbD2.setText(rs.getString("D2"));
               lbD3.setText(rs.getString("D3"));
               lbPromedio.setText(rs.getString("PromedioR"));
               lbSecuencia.setText(rs.getString("Secuencia"));
               lbEquipo.setText(rs.getString("NoEquipo"));
           }
           
       } catch(Exception e) {
           System.out.println("Error en: "+e);
       }
    }//GEN-LAST:event_formWindowOpened

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // Boton Atras regresa al formulario FRegistro
        new FRegistro().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVisualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBlancoFondo;
    private javax.swing.JPanel PanelGuindaFondo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCrra;
    private javax.swing.JLabel lbD1;
    private javax.swing.JLabel lbD2;
    private javax.swing.JLabel lbD3;
    private javax.swing.JLabel lbDep1;
    private javax.swing.JLabel lbDep2;
    private javax.swing.JLabel lbDep3;
    private javax.swing.JLabel lbEqpo;
    private javax.swing.JLabel lbEquipo;
    private javax.swing.JLabel lbImagenUser;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbMtria;
    private javax.swing.JLabel lbNL;
    private javax.swing.JLabel lbNmbre;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumeroLista;
    private javax.swing.JLabel lbPA;
    private javax.swing.JLabel lbPlan;
    private javax.swing.JLabel lbPln;
    private javax.swing.JLabel lbPrmedio;
    private javax.swing.JLabel lbPromedio;
    private javax.swing.JLabel lbSecia;
    private javax.swing.JLabel lbSecuencia;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbSx;
    // End of variables declaration//GEN-END:variables
}
